# Generated by Django 3.1 on 2020-10-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20201001_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backgroundPic',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='twitter.profile')),
                ('following_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='twitter.profile')),
            ],
        ),
    ]
