# Generated by Django 3.1 on 2020-10-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20201003_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_id',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='user_id',
        ),
    ]
