# Generated by Django 3.1 on 2020-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.CharField(choices=[('D', 'Darkmode'), ('L', 'Lightmode')], default='D', max_length=1),
        ),
    ]
